name: Building docker image & push it to the docker hub

env:
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout the code
    - name: Docker Login
      run:
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the docker image
      run: docker build . --file dockerfile --tag dhsoni/test:$(date +%s)
    - name: Docker push
      run: docker push ${{secrets.DOCKER_USERNAME}}/testing


